version: '3.9'

services:
  devooks-database:
    image: postgres:14
    container_name: devooks-database
    environment:
      POSTGRES_DB: "devooksdb"
      POSTGRES_USER: "devooks"
      POSTGRES_PASSWORD: "devooks"
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
