server:
  port: 80

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/devooksdb
    driver: postgresql
    protocol: r2dbc
    host: localhost
    port: 5432
    database: devooksdb
    username: devooks
    password: devooks

  mail:
    host: smtp.gmail.com
    port: 587
    username: email@gmail.com
    password: password
    protocol: smtp
    timeout: 10000
    auth: true
    tls: true
    debug: true

  webflux:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: "file:static/"
  codec:
    max-in-memory-size: 1GB

  flyway:
    url: jdbc:postgresql://localhost:5432/devooksdb
    locations: classpath:/db/migration
    user: devooks
    password: devooks

jwt:
  secretKey:
  accessTokenExpirationHour: 1
  refreshTokenExpirationHour: 720

naver:
  oauthHost: https://nid.naver.com
  profileHost: https://openapi.naver.com
  tokenUrl: /oauth2.0/token
  profileUrl: /v1/nid/me
  clientId:
  clientSecret:
  state: test

kakao:
  oauthHost: https://kauth.kakao.com
  profileHost: https://kapi.kakao.com
  tokenUrl: /oauth/token
  profileUrl: /v2/user/me
  clientId:
  redirectUri:

google:
  oauthHost: https://oauth2.googleapis.com
  profileHost: https://www.googleapis.com
  tokenUrl: /token
  profileUrl: /userinfo/v2/me
  clientId:
  clientSecret:
  redirectUri:

springdoc:
  swagger-ui:
    path: api-docs
