version: '3.9'

services:
  devooks-database:
    image: postgres:14
    container_name: devooks-database
    environment:
      POSTGRES_DB: "devooksdb"
      POSTGRES_USER: "devooks"
      POSTGRES_PASSWORD: "devooks"
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "35432:5432"
  devooks-application:
    image: devooks-backend-app:latest
    build:
      context: .
    container_name: devooks-application
    depends_on:
      - devooks-database
    environment:
      - DATABASE_URL=r2dbc:postgresql://devooks-database:5432/devooksdb
    volumes:
      - ./static:/app/static
    ports:
      - "80:80"
